// HELLO WORLD ACTIONS
export const HELLO_WORLD = 'HELLO_WORLD';
export const HELLO_WORLD_END = 'HELLO_WORLD_END';

// LOGIN ACTIONS
export const DO_LOGIN = 'DO_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

// LOGIN ACTIONS
export const DO_LOGOUT = 'DO_LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';

// LOGIN REGISTER
export const DO_REGISTER = 'DO_REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';


// QUESTIONS ACTIONS
export const GET_ALL_QUESTIONS = 'GET_ALL_QUESTIONS';
export const GET_ALL_QUESTIONS_SUCCESS = 'GET_ALL_QUESTIONS_SUCCESS';
export const GET_ALL_QUESTIONS_ERROR = 'GET_ALL_QUESTIONS_ERROR';

export const ANSWER_QUESTION = 'ANSWER_QUESTION';
export const ANSWER_QUESTION_SUCCESS = 'ANSWER_QUESTION_SUCCESS';
export const ANSWER_QUESTION_ERROR = 'ANSWER_QUESTION_ERROR';

export const ADD_QUESTION = 'ADD_QUESTION';
export const ADD_QUESTION_SUCCESS = 'ADD_QUESTION_SUCCESS';
export const ADD_QUESTION_ERROR = 'ADD_QUESTION_ERROR';

// USER ACTIONS
export const GET_USER = 'GET_USER';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_ERROR = 'GET_USER_ERROR';

export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';
